export const games = [
    {
        id:1,
        type: "Soccer",
        league: "Champions League",
        home: "Milan",
        away: "Napoli",
        homeOdd: '4.90',
        draw: '3.60',
        awayOdd: '1.90',
        homeX: '2.0',
        awayX: '1.23',
        oneTwo: '1.30',
        overZero: '1.12',
        overOne: '1.35',
        overTwo: '1.8',
        overThree: '2.8',
        underZero: '5.0',
        underOne: '2.8',
        underTwo: '1.9',
        underThree: '1.35',
    },
    {
        id:2,
        type: "Soccer",
        league: "Champions League",
        home: "Real Madrid",
        away: "Bayern Munich",
        homeOdd: '2.50',
        draw: '2.90',
        awayOdd: '3.20',
        homeX: '1.30',
        awayX: '1.40',
        oneTwo: '1.35',
        overZero: '1.12',
        overOne: '1.35',
        overTwo: '1.8',
        overThree: '2.8',
        underZero: '5.0',
        underOne: '2.8',
        underTwo: '1.9',
        underThree: '1.35',
    },
    {
        id:3,
        type: "Soccer",
        league: "Champions League",
        home: "Inter",
        away: "PSG",
        homeOdd: '3.50',
        draw: '3.00',
        awayOdd: '2.20',
        homeX: '1.50',
        awayX: '1.25',
        oneTwo: '1.35',
        overZero: '1.12',
        overOne: '1.35',
        overTwo: '1.8',
        overThree: '2.8',
        underZero: '5.0',
        underOne: '2.8',
        underTwo: '1.9',
        underThree: '1.35',
    },
     {
        id:4,
        type: "Soccer",
        league: "Premier League",
        home: "Arsenal",
        away: "West-Ham",
        homeOdd: '1.50',
        draw: '3.00',
        awayOdd: '3.60',
        homeX: '1.13',
        awayX: '1.85',
        oneTwo: '1.2',
        overZero: '1.12',
        overOne: '1.35',
        overTwo: '1.8',
        overThree: '2.8',
        underZero: '5.0',
        underOne: '2.8',
        underTwo: '1.9',
        underThree: '1.35',
    },
    {
        id:5,
        type: "Tennis",
        league: "Wimbledon",
        home: "Novak Dkokovic",
        away: "Carloz Alcaraz",
        homeOdd: '1.50',
        awayOdd: '2.60',
       
    },
]